import { newTime } from "./date-time";

export const fake_schedules_data = [
  {
    id: "a",
    result: [
      {
        courseCode: "CECS 203",
        courseTitle: "",
        section: "01",
        classNum: "5868",
        type: "SEM",
        days: ["m", "w"],
        startTime: newTime("08:30"),
        endTime: newTime("12:45"),
        openSeats: "Seats available",
        location: "ONLINE",
        instructor: "Lacey",
        notes: "",
      },
      {
        courseCode: "BIO 216",
        courseTitle: "",
        section: "05",
        classNum: "8913",
        type: "SEM",
        days: ["m", "w"],
        startTime: newTime("14:00"),
        endTime: newTime("15:30"),
        openSeats: "Seats available",
        location: "ONLINE",
        instructor: "Jane",
        notes: "",
      },
      {
        courseCode: "ENGR 410",
        courseTitle: "",
        section: "01",
        classNum: "2684",
        type: "SEM",
        days: ["t", "th"],
        startTime: newTime("11:00"),
        endTime: newTime("12:30"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
      {
        courseCode: "BASK 101",
        courseTitle: "",
        section: "09",
        classNum: "8970",
        type: "SEM",
        days: ["t", "th"],
        startTime: newTime("16:30"),
        endTime: newTime("18:45"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
      {
        courseCode: "HELL 666",
        courseTitle: "",
        section: "06",
        classNum: "6666",
        type: "LAB",
        days: ["sa"],
        startTime: newTime("8:00"),
        endTime: newTime("17:00"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
    ],
  },
  //////////////////////////////////////////////////////////////////
  {
    id: "b",
    result: [
      {
        courseCode: "CECS 424",
        courseTitle: "",
        section: "11",
        classNum: "1689",
        type: "SEM",
        days: ["t", "th"],
        startTime: newTime("06:30"),
        endTime: newTime("08:45"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
      {
        courseCode: "BIO 216",
        courseTitle: "",
        section: "06",
        classNum: "5682",
        type: "SEM",
        days: ["t", "th"],
        startTime: newTime("10:00"),
        endTime: newTime("12:00"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
      {
        courseCode: "BASK 101",
        courseTitle: "",
        section: "03",
        classNum: "2389",
        type: "SEM",
        days: ["t", "th"],
        startTime: newTime("14:00"),
        endTime: newTime("16:30"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
      {
        courseCode: "ME",
        courseTitle: "",
        section: "01",
        classNum: "2089",
        type: "SEM",
        days: ["f"],
        startTime: newTime("08:00"),
        endTime: newTime("12:30"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
      {
        courseCode: "ENGR 410",
        courseTitle: "",
        section: "03",
        classNum: "2088",
        type: "SEM",
        days: ["m", "w"],
        startTime: newTime("08:00"),
        endTime: newTime("10:30"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
    ],
  },
  //////////////////////////////////////////////////////////////////
  {
    id: "c",
    result: [
      {
        courseCode: "CECS 424",
        courseTitle: "",
        section: "02",
        classNum: "0894",
        type: "SEM",
        days: ["m", "w"],
        startTime: newTime("08:00"),
        endTime: newTime("09:30"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
      {
        courseCode: "BIO 216",
        courseTitle: "",
        section: "01",
        classNum: "4891",
        type: "SEM",
        days: ["m", "w"],
        startTime: newTime("11:00"),
        endTime: newTime("13:30"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
      {
        courseCode: "ENGR 410",
        courseTitle: "",
        section: "02",
        classNum: "8980",
        type: "SEM",
        days: ["m", "w"],
        startTime: newTime("15:00"),
        endTime: newTime("16:00"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
    ],
  },
  //////////////////////////////////////////////////////////////////
  {
    id: "d",
    result: [
      {
        courseCode: "CECS 424",
        courseTitle: "",
        section: "08",
        classNum: "0569",
        type: "SEM",
        days: ["m", "w"],
        startTime: newTime("09:00"),
        endTime: newTime("10:00"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
      {
        courseCode: "CECS 203",
        courseTitle: "",
        section: "06",
        classNum: "5588",
        type: "SEM",
        days: ["m", "w"],
        startTime: newTime("10:30"),
        endTime: newTime("12:00"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
      {
        courseCode: "BASK 101",
        courseTitle: "",
        section: "01",
        classNum: "6984",
        type: "SEM",
        days: ["m", "w"],
        startTime: newTime("13:00"),
        endTime: newTime("15:30"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
      {
        courseCode: "GEOG 516",
        courseTitle: "",
        section: "01",
        classNum: "4444",
        type: "SEM",
        days: ["t", "th"],
        startTime: newTime("09:00"),
        endTime: newTime("11:30"),
        openSeats: "Seats available",
        location: "",
        instructor: "",
        notes: "",
      },
    ],
  },
];
